# Generated by Django 6.0.2 on 2026-03-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_notification'),
        ('items', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('claim_received', 'Someone claimed your item'), ('claim_approved', 'Your claim was approved'), ('claim_rejected', 'Your claim was rejected'), ('item_match', 'A found item matches your lost report'), ('item_deleted', 'Your item was deleted by admin')], default='claim_received', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
        ),
    ]
